import { Navigation } from './components/Navigation.jsx'

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<title>My first app with Next 13</title>
			<body>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
